// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmHrpTY1LvItbxasU1TueHik8QZ2vh-No',
    appId: '1:997420411312:web:5cf1dae308d64c7e180e75',
    messagingSenderId: '997420411312',
    projectId: 'gakumon-app',
    authDomain: 'gakumon-app.firebaseapp.com',
    storageBucket: 'gakumon-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6kzSQbQPtA8ihusLEOWNTIyW2CXXtnOs',
    appId: '1:997420411312:android:3514edd97e77ba7b180e75',
    messagingSenderId: '997420411312',
    projectId: 'gakumon-app',
    storageBucket: 'gakumon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATyVgx6Pa5-vG7VLz2FAWNi4TlIsdim-A',
    appId: '1:997420411312:ios:7926243787083309180e75',
    messagingSenderId: '997420411312',
    projectId: 'gakumon-app',
    storageBucket: 'gakumon-app.firebasestorage.app',
    iosBundleId: 'com.example.gakumonApp01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATyVgx6Pa5-vG7VLz2FAWNi4TlIsdim-A',
    appId: '1:997420411312:ios:7926243787083309180e75',
    messagingSenderId: '997420411312',
    projectId: 'gakumon-app',
    storageBucket: 'gakumon-app.firebasestorage.app',
    iosBundleId: 'com.example.gakumonApp01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmHrpTY1LvItbxasU1TueHik8QZ2vh-No',
    appId: '1:997420411312:web:d70421fcbcd7d5c6180e75',
    messagingSenderId: '997420411312',
    projectId: 'gakumon-app',
    authDomain: 'gakumon-app.firebaseapp.com',
    storageBucket: 'gakumon-app.firebasestorage.app',
  );
}
